### PR TITLE
add missing database config for local db

### PR DESCRIPTION
**Pull request by rjnienaber**
I've generated this migration script by adding changes until the mysql database schema dump matches what @poma posted in Discord. While there may be some ordering differences with enumerations/indexes, I don't think they're material. 

This migration should not be run on the production database as I believe it will fail. Instead, the below query should be run:

```
INSERT INTO migrations (migration, batch)
  SELECT '2020_01_03_104229_add_missing_database_config', MAX(batch) + 1
  FROM migrations;
```

### CODE REVIEW

**Comment by poma** [comment]
String length are different because of https://github.com/hotsapi/hotsapi/blob/master/app/Providers/AppServiceProvider.php#L36 but I forgot why exactly did I add that

**Comment by poma** [comment]
Ok I found why it was 191, changed

```
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
```

in db config, now the schema should be closer to prod by default. Looking at other changes

**Comment by poma** [comment]
For scores, looks like the ones that are currently in code are more correct and prod schema should be changed instead

**Comment by rjnienaber** [comment]
> Users and password_resets tables are never used and need to be dropped (just did that on prod)

The process I was hoping to follow was to get the local and prod db schema identical and then moving forward start using migrations to keep them in sync.

Not sure what next steps should be with this.

**Comment by poma** [comment]
oh ok we can change schema to get in sync and then change some things back in both prod and this repo. With string length though try to do a fresh migration from master. I've changed default length back to 255, so this should remove a bunch of differences.

**Comment by rjnienaber** [comment]
I'm not sure if [the change of charset](https://github.com/hotsapi/hotsapi/commit/37167c8f8a7ad38d19fb4caaed940c78ece9dcc4#diff-8a025ad5d4f4fade612727b1bb0e974fR51) is required. It seems like there are [valid reasons](https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci/766996#766996) to prefer `utf8mb4`/`utf8mb4_unicode_ci`. I think `utf8mb4` might be more future proof when it comes to things like new emojis.

**Comment by MGatner** [comment]
Definitely use `utf8mb4`. It helps with all the foreign BattleTags as well. Blizz is pretty lenient about characters in Battle.net names.

**Comment by rjnienaber** [comment]
Not much development on HotsApi so closing this

**Pull request closed without merging**
